# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "b2bdev"
client_id = "ff93653f637a8a6b5a88fee3766d259b"
application_url = "https://onshore-embezzle-skinny.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_companies,write_companies"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
